/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as DashboardUploadRouteImport } from './routes/dashboard.upload'
import { Route as DashboardQuestionsRouteImport } from './routes/dashboard.questions'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as DashboardChangePasswordRouteImport } from './routes/dashboard.change-password'
import { Route as DashboardBanksRouteImport } from './routes/dashboard.banks'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardExamAttemptIdRouteImport } from './routes/dashboard.exam.$attemptId'
import { Route as DashboardBanksBankIdRouteImport } from './routes/dashboard.banks.$bankId'
import { Route as DashboardExamAttemptIdReviewRouteImport } from './routes/dashboard.exam.$attemptId.review'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUploadRoute = DashboardUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuestionsRoute = DashboardQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChangePasswordRoute = DashboardChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBanksRoute = DashboardBanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExamAttemptIdRoute = DashboardExamAttemptIdRouteImport.update({
  id: '/exam/$attemptId',
  path: '/exam/$attemptId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBanksBankIdRoute = DashboardBanksBankIdRouteImport.update({
  id: '/$bankId',
  path: '/$bankId',
  getParentRoute: () => DashboardBanksRoute,
} as any)
const DashboardExamAttemptIdReviewRoute =
  DashboardExamAttemptIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => DashboardExamAttemptIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/banks': typeof DashboardBanksRouteWithChildren
  '/dashboard/change-password': typeof DashboardChangePasswordRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/questions': typeof DashboardQuestionsRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/banks/$bankId': typeof DashboardBanksBankIdRoute
  '/dashboard/exam/$attemptId': typeof DashboardExamAttemptIdRouteWithChildren
  '/dashboard/exam/$attemptId/review': typeof DashboardExamAttemptIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/banks': typeof DashboardBanksRouteWithChildren
  '/dashboard/change-password': typeof DashboardChangePasswordRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/questions': typeof DashboardQuestionsRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/banks/$bankId': typeof DashboardBanksBankIdRoute
  '/dashboard/exam/$attemptId': typeof DashboardExamAttemptIdRouteWithChildren
  '/dashboard/exam/$attemptId/review': typeof DashboardExamAttemptIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/banks': typeof DashboardBanksRouteWithChildren
  '/dashboard/change-password': typeof DashboardChangePasswordRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/questions': typeof DashboardQuestionsRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/banks/$bankId': typeof DashboardBanksBankIdRoute
  '/dashboard/exam/$attemptId': typeof DashboardExamAttemptIdRouteWithChildren
  '/dashboard/exam/$attemptId/review': typeof DashboardExamAttemptIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/features'
    | '/pricing'
    | '/dashboard/admin'
    | '/dashboard/banks'
    | '/dashboard/change-password'
    | '/dashboard/history'
    | '/dashboard/profile'
    | '/dashboard/questions'
    | '/dashboard/upload'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/banks/$bankId'
    | '/dashboard/exam/$attemptId'
    | '/dashboard/exam/$attemptId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/features'
    | '/pricing'
    | '/dashboard/admin'
    | '/dashboard/banks'
    | '/dashboard/change-password'
    | '/dashboard/history'
    | '/dashboard/profile'
    | '/dashboard/questions'
    | '/dashboard/upload'
    | '/dashboard/users'
    | '/dashboard'
    | '/dashboard/banks/$bankId'
    | '/dashboard/exam/$attemptId'
    | '/dashboard/exam/$attemptId/review'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/features'
    | '/pricing'
    | '/dashboard/admin'
    | '/dashboard/banks'
    | '/dashboard/change-password'
    | '/dashboard/history'
    | '/dashboard/profile'
    | '/dashboard/questions'
    | '/dashboard/upload'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/banks/$bankId'
    | '/dashboard/exam/$attemptId'
    | '/dashboard/exam/$attemptId/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FeaturesRoute: typeof FeaturesRoute
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/upload': {
      id: '/dashboard/upload'
      path: '/upload'
      fullPath: '/dashboard/upload'
      preLoaderRoute: typeof DashboardUploadRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/questions': {
      id: '/dashboard/questions'
      path: '/questions'
      fullPath: '/dashboard/questions'
      preLoaderRoute: typeof DashboardQuestionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/change-password': {
      id: '/dashboard/change-password'
      path: '/change-password'
      fullPath: '/dashboard/change-password'
      preLoaderRoute: typeof DashboardChangePasswordRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/banks': {
      id: '/dashboard/banks'
      path: '/banks'
      fullPath: '/dashboard/banks'
      preLoaderRoute: typeof DashboardBanksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/exam/$attemptId': {
      id: '/dashboard/exam/$attemptId'
      path: '/exam/$attemptId'
      fullPath: '/dashboard/exam/$attemptId'
      preLoaderRoute: typeof DashboardExamAttemptIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/banks/$bankId': {
      id: '/dashboard/banks/$bankId'
      path: '/$bankId'
      fullPath: '/dashboard/banks/$bankId'
      preLoaderRoute: typeof DashboardBanksBankIdRouteImport
      parentRoute: typeof DashboardBanksRoute
    }
    '/dashboard/exam/$attemptId/review': {
      id: '/dashboard/exam/$attemptId/review'
      path: '/review'
      fullPath: '/dashboard/exam/$attemptId/review'
      preLoaderRoute: typeof DashboardExamAttemptIdReviewRouteImport
      parentRoute: typeof DashboardExamAttemptIdRoute
    }
  }
}

interface DashboardBanksRouteChildren {
  DashboardBanksBankIdRoute: typeof DashboardBanksBankIdRoute
}

const DashboardBanksRouteChildren: DashboardBanksRouteChildren = {
  DashboardBanksBankIdRoute: DashboardBanksBankIdRoute,
}

const DashboardBanksRouteWithChildren = DashboardBanksRoute._addFileChildren(
  DashboardBanksRouteChildren,
)

interface DashboardExamAttemptIdRouteChildren {
  DashboardExamAttemptIdReviewRoute: typeof DashboardExamAttemptIdReviewRoute
}

const DashboardExamAttemptIdRouteChildren: DashboardExamAttemptIdRouteChildren =
  {
    DashboardExamAttemptIdReviewRoute: DashboardExamAttemptIdReviewRoute,
  }

const DashboardExamAttemptIdRouteWithChildren =
  DashboardExamAttemptIdRoute._addFileChildren(
    DashboardExamAttemptIdRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardBanksRoute: typeof DashboardBanksRouteWithChildren
  DashboardChangePasswordRoute: typeof DashboardChangePasswordRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardQuestionsRoute: typeof DashboardQuestionsRoute
  DashboardUploadRoute: typeof DashboardUploadRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardExamAttemptIdRoute: typeof DashboardExamAttemptIdRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardBanksRoute: DashboardBanksRouteWithChildren,
  DashboardChangePasswordRoute: DashboardChangePasswordRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardQuestionsRoute: DashboardQuestionsRoute,
  DashboardUploadRoute: DashboardUploadRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardExamAttemptIdRoute: DashboardExamAttemptIdRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FeaturesRoute: FeaturesRoute,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
